apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp-api
  template:
    metadata:
      labels:
        app: todoapp-api
    spec:
      containers:
        - name: todoapp-api
          image: todoappacrmunish.azurecr.io/todoapp-api:1.5
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-api-service
spec:
  type: LoadBalancer
  selector:
    app: todoapp-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080